# .pre-commit-config.yaml
default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: examples/|docs/|docs_source/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: examples/|docs/|docs_source/
        args: [
            "--max-line-length=99",
            "--ignore=E203,E704,W503",
            "--statistics",
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: examples/|docs/|docs_source/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [
          "alembic>=1.5.0",
          "colorlog",
          "numpy",
          "packaging>=20.0",
          "sqlalchemy>=1.3.0",
          "tqdm",
          "PyYAML",
          "mypy_boto3_s3",
          "types-PyYAML",
          "types-redis",
          "types-setuptools",
          "types-tqdm",
          "typing_extensions>=3.10.0.0",
        ]
        exclude: examples/|docs/|docs_source/
        args: [
          --warn-unused-configs,
          --disallow-untyped-calls,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --no-implicit-optional,
          --warn-redundant-casts,
          --strict-equality,
          --extra-checks,
          --no-implicit-reexport,
          --ignore-missing-imports,
        ]